name: todo_task
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_native_splash: ^2.4.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_assets:
  output_path: lib/core/images/
  filename: app_images.dart
  assets_path:
    - assets/images/
    - assets/svgs/
  classname: AppImages
